[package]
name = "printf"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Format and print data - Windows optimized"

[[bin]]
name = "printf"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
rayon.workspace = true

# Link to original uutils implementation for fallback
uu_printf = { path = "../../../../src/uu/printf" }
