[package]
name = "df"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Display filesystem usage - Windows optimized"

[[bin]]
name = "df"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true
chrono.workspace = true

# Link to original uutils implementation for fallback
uu_df = { path = "../../../../src/uu/df" }
