[package]
name = "basenc"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Multi-base encoding - Windows optimized"

[[bin]]
name = "basenc"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true

# Link to original uutils implementation for fallback
uu_basenc = { path = "../../../../src/uu/basenc" }
