[package]
name = "basename"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Extract filename from path - Windows optimized"

[[bin]]
name = "basename"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true

# Link to original uutils implementation for fallback
uu_basename = { path = "../../../../src/uu/basename" }
