[package]
name = "more"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Page through text - Windows optimized"

[[bin]]
name = "more"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
rayon.workspace = true
memmap2.workspace = true
memchr.workspace = true
regex.workspace = true

# Link to original uutils implementation for fallback
uu_more = { path = "../../../../src/uu/more" }
