#!/bin/bash
# Install Windows-optimized coreutils to system PATH

INSTALL_DIR="${1:-C:/utils/winutils}"

echo "📦 Installing Windows-optimized coreutils to $INSTALL_DIR..."

mkdir -p "$INSTALL_DIR"

# Copy binaries
cp target/release/tac.exe "$INSTALL_DIR/"
cp target/release/cksum.exe "$INSTALL_DIR/"
cp target/release/numfmt.exe "$INSTALL_DIR/"
cp target/release/date.exe "$INSTALL_DIR/"
cp target/release/cut.exe "$INSTALL_DIR/"
cp target/release/true.exe "$INSTALL_DIR/"
cp target/release/unlink.exe "$INSTALL_DIR/"
cp target/release/dircolors.exe "$INSTALL_DIR/"
cp target/release/tr.exe "$INSTALL_DIR/"
cp target/release/seq.exe "$INSTALL_DIR/"
cp target/release/sync.exe "$INSTALL_DIR/"
cp target/release/rmdir.exe "$INSTALL_DIR/"
cp target/release/du.exe "$INSTALL_DIR/"
cp target/release/vdir.exe "$INSTALL_DIR/"
cp target/release/dd.exe "$INSTALL_DIR/"
cp target/release/uniq.exe "$INSTALL_DIR/"
cp target/release/yes.exe "$INSTALL_DIR/"
cp target/release/sort.exe "$INSTALL_DIR/"
cp target/release/cat.exe "$INSTALL_DIR/"
cp target/release/ptx.exe "$INSTALL_DIR/"
cp target/release/base64.exe "$INSTALL_DIR/"
cp target/release/realpath.exe "$INSTALL_DIR/"
cp target/release/rm.exe "$INSTALL_DIR/"
cp target/release/nl.exe "$INSTALL_DIR/"
cp target/release/shuf.exe "$INSTALL_DIR/"
cp target/release/mkdir.exe "$INSTALL_DIR/"
cp target/release/split.exe "$INSTALL_DIR/"
cp target/release/more.exe "$INSTALL_DIR/"
cp target/release/echo.exe "$INSTALL_DIR/"
cp target/release/shred.exe "$INSTALL_DIR/"
cp target/release/readlink.exe "$INSTALL_DIR/"
cp target/release/ln.exe "$INSTALL_DIR/"
cp target/release/env.exe "$INSTALL_DIR/"
cp target/release/fold.exe "$INSTALL_DIR/"
cp target/release/hashsum.exe "$INSTALL_DIR/"
cp target/release/truncate.exe "$INSTALL_DIR/"
cp target/release/printf.exe "$INSTALL_DIR/"
cp target/release/base32.exe "$INSTALL_DIR/"
cp target/release/head.exe "$INSTALL_DIR/"
cp target/release/fmt.exe "$INSTALL_DIR/"
cp target/release/od.exe "$INSTALL_DIR/"
cp target/release/test.exe "$INSTALL_DIR/"
cp target/release/hostname.exe "$INSTALL_DIR/"
cp target/release/link.exe "$INSTALL_DIR/"
cp target/release/df.exe "$INSTALL_DIR/"
cp target/release/false.exe "$INSTALL_DIR/"
cp target/release/csplit.exe "$INSTALL_DIR/"
cp target/release/whoami.exe "$INSTALL_DIR/"
cp target/release/pwd.exe "$INSTALL_DIR/"
cp target/release/comm.exe "$INSTALL_DIR/"
cp target/release/dir.exe "$INSTALL_DIR/"
cp target/release/basename.exe "$INSTALL_DIR/"
cp target/release/mv.exe "$INSTALL_DIR/"
cp target/release/factor.exe "$INSTALL_DIR/"
cp target/release/nproc.exe "$INSTALL_DIR/"
cp target/release/printenv.exe "$INSTALL_DIR/"
cp target/release/tsort.exe "$INSTALL_DIR/"
cp target/release/unexpand.exe "$INSTALL_DIR/"
cp target/release/sleep.exe "$INSTALL_DIR/"
cp target/release/tail.exe "$INSTALL_DIR/"
cp target/release/basenc.exe "$INSTALL_DIR/"
cp target/release/join.exe "$INSTALL_DIR/"
cp target/release/arch.exe "$INSTALL_DIR/"
cp target/release/mktemp.exe "$INSTALL_DIR/"
cp target/release/wc.exe "$INSTALL_DIR/"
cp target/release/dirname.exe "$INSTALL_DIR/"
cp target/release/expr.exe "$INSTALL_DIR/"
cp target/release/paste.exe "$INSTALL_DIR/"
cp target/release/sum.exe "$INSTALL_DIR/"
cp target/release/cp.exe "$INSTALL_DIR/"
cp target/release/expand.exe "$INSTALL_DIR/"
cp target/release/tee.exe "$INSTALL_DIR/"
cp target/release/touch.exe "$INSTALL_DIR/"
cp target/release/pr.exe "$INSTALL_DIR/"

echo "✅ Installation complete!"
echo "Add $INSTALL_DIR to your PATH to use the utilities"
