[package]
name = "dircolors"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Setup colors for ls - Windows optimized"

[[bin]]
name = "dircolors"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true
rayon.workspace = true
walkdir.workspace = true
tempfile.workspace = true

# Link to original uutils implementation for fallback
uu_dircolors = { path = "../../../../src/uu/dircolors" }
