[package]
name = "tsort"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Topological sort - Windows optimized"

[[bin]]
name = "tsort"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
rayon.workspace = true

# Link to original uutils implementation for fallback
uu_tsort = { path = "../../../../src/uu/tsort" }
