[package]
name = "unlink"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Remove single file - Windows optimized"

[[bin]]
name = "unlink"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true
rayon.workspace = true
walkdir.workspace = true
tempfile.workspace = true

# Link to original uutils implementation for fallback
uu_unlink = { path = "../../../../src/uu/unlink" }
