[package]
name = "sleep"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Delay execution - Windows optimized"

[[bin]]
name = "sleep"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true

# Link to original uutils implementation for fallback
uu_sleep = { path = "../../../../src/uu/sleep" }
