[package]
name = "link"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Create hard links - Windows optimized"

[[bin]]
name = "link"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true
rayon.workspace = true
walkdir.workspace = true
tempfile.workspace = true

# Link to original uutils implementation for fallback
uu_link = { path = "../../../../src/uu/link" }
