[package]
name = "uniq"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Remove duplicate lines - Windows optimized"

[[bin]]
name = "uniq"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
rayon.workspace = true
memmap2.workspace = true
memchr.workspace = true
regex.workspace = true

# Link to original uutils implementation for fallback
uu_uniq = { path = "../../../../src/uu/uniq" }
