[package]
name = "seq"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Generate sequence of numbers - Windows optimized"

[[bin]]
name = "seq"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
rayon.workspace = true

# Link to original uutils implementation for fallback
uu_seq = { path = "../../../../src/uu/seq" }
