[package]
name = "dir"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "List directory contents (Windows style) - Windows optimized"

[[bin]]
name = "dir"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true
rayon.workspace = true
walkdir.workspace = true
tempfile.workspace = true

# Link to original uutils implementation for fallback
uu_dir = { path = "../../../../src/uu/dir" }
