[package]
name = "numfmt"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Format numbers - Windows optimized"

[[bin]]
name = "numfmt"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
rayon.workspace = true

# Link to original uutils implementation for fallback
uu_numfmt = { path = "../../../../src/uu/numfmt" }
