[package]
name = "nl"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Number lines - Windows optimized"

[[bin]]
name = "nl"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
rayon.workspace = true
memmap2.workspace = true
memchr.workspace = true
regex.workspace = true

# Link to original uutils implementation for fallback
uu_nl = { path = "../../../../src/uu/nl" }
