# Project-specific Cargo configuration for mistral.rs
# Optimized for CUDA builds on Windows with sccache and fast linking

[build]
# Use local target directory (overrides CARGO_TARGET_DIR env var if set in config.toml)
# Note: Environment variable CARGO_TARGET_DIR takes precedence over this setting
# For local builds, ensure CARGO_TARGET_DIR is NOT set in environment
target-dir = "target"

# Use sccache for compilation caching (30-80% faster rebuilds)
# Note: sccache is disabled during coverage builds via --no-cfg-coverage
rustc-wrapper = "sccache"

# Parallel compilation jobs
jobs = 8

[env]
# sccache configuration
RUSTC_WRAPPER = "sccache"
SCCACHE_DIR = "T:\\projects\\rust-mistral\\sccache-cache"
SCCACHE_CACHE_SIZE = "20G"
SCCACHE_IDLE_TIMEOUT = "3600"
SCCACHE_DIRECT = "true"

# IMPORTANT: Incremental compilation is disabled for sccache compatibility
# cargo-llvm-cov will override this to "1" automatically
CARGO_INCREMENTAL = "0"

# CUDA/cuDNN/MKL runtime paths
CUDA_PATH = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9"
CUDNN_PATH = "C:\\Program Files\\NVIDIA\\CUDNN\\v9.8"
CUDNN_LIB = "C:\\Program Files\\NVIDIA\\CUDNN\\v9.8\\lib\\12.8\\x64"
MKLROOT = "C:\\Program Files (x86)\\Intel\\oneAPI\\mkl\\latest"

[target.x86_64-pc-windows-msvc]
# Use rust-lld for 30-50% faster linking than link.exe
linker = "rust-lld.exe"
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=/INCREMENTAL:NO",
    "-C", "link-arg=/OPT:REF",
    "-C", "link-arg=/OPT:ICF",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+aes,+sha2,+fp16",
]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=-avx,-avx2",
]

# Profile configurations
[profile.dev]
# Development profile with debug info
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
incremental = true  # Enable incremental for dev builds

[profile.release]
# Release profile with optimizations
opt-level = 3
lto = "thin"
debug = false
incremental = false

[profile.test]
# Test profile inherits from dev but can be customized
inherits = "dev"
opt-level = 0

[profile.bench]
# Benchmark profile inherits from release
inherits = "release"
