[package]
name = "pwd"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Print working directory - Windows optimized"

[[bin]]
name = "pwd"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true

# Link to original uutils implementation for fallback
uu_pwd = { path = "../../../../src/uu/pwd" }
