[package]
name = "false"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Return false exit code - Windows optimized"

[[bin]]
name = "false"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true

# Link to original uutils implementation for fallback
uu_false = { path = "../../../../src/uu/false" }
