[package]
name = "uu_where"
version = "0.1.0"
authors = ["David Martel <david.martel@auricleinc.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "High-performance Windows where command implementation"
homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils"
keywords = ["coreutils", "windows", "where", "path", "executable"]
categories = ["command-line-utilities"]

[[bin]]
name = "where"
path = "src/main.rs"

[dependencies]
# Core dependencies
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env", "wrap_help"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.35", features = ["full"] }

# Windows-specific
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_SystemInformation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_UI_Shell",
]}
winapi-util = "0.1"

# Path handling
dunce = "1.0"
path-slash = "0.2"
normalize-path = "0.2"

# Performance
rayon = { version = "1.8", optional = true }
crossbeam-channel = "0.5"
dashmap = "5.5"
lru = "0.12"
memchr = "2.7"
ahash = "0.8"
parking_lot = "0.12"

# Utilities
regex = "1.10"
glob = "0.3"
walkdir = "2.4"
dirs = "5.0"
which = "6.0"
shell-words = "1.1"
termcolor = "1.4"
once_cell = "1.19"

# Additional dependencies for where functionality
chrono = { version = "0.4", features = ["serde"] }
humansize = "2.1"

[dev-dependencies]
tempfile = "3.8"
assert_cmd = "2.0"
predicates = "3.0"

[features]
default = ["parallel"]
parallel = ["dep:rayon"]
tracing = ["dep:tracing", "dep:tracing-subscriber"]

[dependencies.tracing]
version = "0.1"
optional = true

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter", "fmt"]
optional = true

[build-dependencies]
chrono = { version = "0.4", features = ["serde"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[profile.release-fast]
inherits = "release"
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
