[package]
name = "ln"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Create links - Windows optimized"

[[bin]]
name = "ln"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true
rayon.workspace = true
memmap2.workspace = true
walkdir.workspace = true
tempfile.workspace = true

# Link to original uutils implementation for fallback
uu_ln = { path = "../../../../src/uu/ln" }
