[package]
name = "whoami"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Display current username - Windows optimized"

[[bin]]
name = "whoami"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true
chrono.workspace = true

# Link to original uutils implementation for fallback
uu_whoami = { path = "../../../../src/uu/whoami" }
