# ast-grep configuration for mistral.rs
# See https://ast-grep.github.io/guide/rule-config.html

ruleDirs:
  - rules

testConfigs:
  - testDir: test

# Language-specific settings
languageGlobs:
  rust:
    - "**/*.rs"
  python:
    - "**/*.py"
  javascript:
    - "**/*.js"
    - "**/*.cjs"
    - "**/*.mjs"
  ts:
    - "**/*.ts"
    - "**/*.tsx"

# Ignore patterns
ignore:
  - "**/target/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/.venv/**"
  - "**/build/**"
  - "**/.git/**"
