[package]
name = "nproc"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Display number of processors - Windows optimized"

[[bin]]
name = "nproc"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
thiserror.workspace = true
windows.workspace = true
chrono.workspace = true

# Link to original uutils implementation for fallback
uu_nproc = { path = "../../../../src/uu/nproc" }
