[package]
name = "ls"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "List directory contents - Windows optimized"

[[bin]]
name = "ls"
path = "src/main.rs"

[dependencies]
clap.workspace = true
uucore.workspace = true
winpath.workspace = true
winutils-core.workspace = true
thiserror.workspace = true
regex.workspace = true
walkdir.workspace = true
chrono.workspace = true

# Link to original uutils implementation for fallback
uu_ls = { path = "../../../../src/uu/ls" }
