name: deploy_cpu_docker

# gh workflow run deploy_cpu_docker
# This also runs on release deploy
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
    build-and-push-image:
        runs-on: [ubuntu-latest]
        permissions:
            contents: write
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write
            security-events: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Initialize Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                install: true

            - name: Inject slug/short variables
              uses: rlespinasse/github-slug-action@v4.5.0

            - name: Login to GitHub Container Registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta-cpu
              uses: docker/metadata-action@v5
              with:
                  images: |
                    ghcr.io/${{env.GITHUB_REPOSITORY_OWNER_PART}}/${{env.GITHUB_REPOSITORY_NAME_PART}}
                  flavor: |
                    latest=false
                  tags: |
                    type=semver,pattern=cpu-{{version}}
                    type=semver,pattern=cpu-{{major}}.{{minor}}
                    type=raw,value=cpu-latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
                    type=raw,value=cpu-sha-${{ env.GITHUB_SHA_SHORT }}
            - name: Build and push Docker image
              id: build-and-push-cpu
              uses: docker/build-push-action@v6
              with:
                context: .
                file: Dockerfile
                push: ${{ github.event_name != 'pull_request' }}
                platforms: 'linux/amd64'
                tags: ${{ steps.meta-cpu.outputs.tags }}
                labels: ${{ steps.meta-cpu.outputs.labels }}
